version: '3'
services:

  #PHP Service
  app:
    image: test:app
    container_name: app
    tty: true
    volumes:
      - ./iot-annotation:/var/www/html
    environment:
      SERVICE_NAME: app
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: test:nginx
    container_name: webserver
    tty: true
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mariadb
    container_name: db
    tty: true
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./configs/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      SERVICE_NAME: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge