FROM php:fpm

RUN docker-php-ext-install pdo_mysql

RUN apt-get update && apt-get install -y git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html
COPY ./iot-annotation .
RUN composer install
RUN chmod +x ./console

EXPOSE 9000

CMD ["php-fpm"]