version: '3'
services:

  #PHP Service
  app:
    build:
        context: ./
        dockerfile: Dockerfile-fpm
    image: test:app
    container_name: app
    tty: true
    volume:
      - ./iot-annotation:/var/www/html
    environment:
      SERVICE_NAME: app
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
        context: ./
        dockerfile: Dockerfile-nginx
    image: test:nginx
    container_name: webserver
    tty: true
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mariadb
    container_name: db
    tty: true
    environment:
      SERVICE_NAME: db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: iot_annotation
      MYSQL_DATABASE: iot_annotation
      MYSQL_PASSWORD: secret
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge