version: '3'
services:

  # PHP Service
  app:
    image: test:app
    container_name: app
    build:
      context: ./php-fpm
    tty: true
    volumes:
      - app-volume:/var/www/html
    networks:
      - app-network

  # Composer
  composer:
    image: test:composer
    container_name: composer
    build:
      context: ./composer
    tty: true
    volumes:
      - app-volume:/var/www/html

  # Nginx Service
  webserver:
    image: test:nginx
    container_name: webserver
    build:
      context: ./nginx
    tty: true
    volumes:
      - app-volume:/var/www/html
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - app-network

  # MySQL Service
  db:
    image: test:mariadb
    container_name: db
    build:
      context: ./mariadb
    tty: true
    volumes:
      - ./mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

# Docker Volumes
volumes:
  app-volume:

# Docker Networks
networks:
  app-network:
    driver: bridge