version: '3'
services:

  #PHP Service
  app:
    image: test:app
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile-fpm
    tty: true
    volumes:
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
      - ./iot-annotation:/var/www/html
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: test:nginx
    container_name: webserver
    tty: true
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./iot-annotation/public:/var/www/html/public
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mariadb
    container_name: db
    tty: true
    volumes:
      - ./configs/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge